### ISSUE TITLE
Research: File upload by an administrator 

### ISSUE THREAD

**Issue by KasiaIST303** [eclatealba/QuizMasters#29]
Improvement suggested during Part C review.
Would introduce a new experience for a system administrator to have the ability to upload a new set of test questions. 
1.	create a web based upload for a csv file 
2.	append the contents of the csv file to the questions table in sqlite 

Reference used for planning:
https://medevel.com/flask-tutorial-upload-csv-file-and-insert-rows-into-the-database/
https://mungingdata.com/sqlite/create-database-load-csv-python/

**Comment by UTEDB-QPNF5-GV8JM-4SWBV-8XE7** [comment]
> Improvement suggested during Part C review. Would introduce a new experience for a system administrator to have the ability to upload a new set of test questions.
> 
> 1. create a web based upload for a csv file
> 2. append the contents of the csv file to the questions table in sqlite
> 
> Reference used for planning: https://medevel.com/flask-tutorial-upload-csv-file-and-insert-rows-into-the-database/ https://mungingdata.com/sqlite/create-database-load-csv-python/
